# 1.0 Intro to Financial Concepts using Python

In [1]:
import numpy as np
import scipy as sp

## ROI: Return on investment (% gain)

$ return = \frac{v_{t2}-v_{t1}}{v_{t1}} = r $

- $v_{t1}$: investment initial value
- $v_{t2}$: investment final value

In [2]:
def percent_gain(pv, fv, displayPercent=True):
    """
    Returns the percent gain from investment
    
    Parameters
    ----------
    pv: int / float
        Investment's initial value
    fv: int / float
        Investment's final value
    displayPercent: bool
        0 returns result in float format, while 1 returns result in percent format
    """
    if not all(isinstance(i, (int, float)) for i in [pv,fv]): 
        raise TypeError('pv and fv must be int/float datatype')
    elif not isinstance(displayPercent, (bool)):
        raise TypeError('displayPercent value must be bool datatype')
    elif displayPercent is True:
        return 'The return on investment is {0}%'.format(str((fv-pv)/pv * 100))
    elif displayPercent is not True:
        return 'The return on investment is {0}'.format((fv-pv)/pv)
    else:
        raise Exception('Unknown error, please check the function and values')

You invest `$10,000` and it's worth `$11,000` after 1 year, what's the interest rate?

In [3]:
percent_gain(10000,11000)

'The return on investment is 10.0%'

In [4]:
percent_gain(10000,11000,False)

'The return on investment is 0.1'

## ROI: Return on investment (Dollar Value)

$ v_{t2} = v_{t1} * (1+r) $

- `r`: the rate of return of the investment per period t

Assuming you invest `$10,000` and the ARR=`10%`, what do you get after 1 year?

In [5]:
np.fv(0.1, 1, 0, -10000)

11000.0

## Cumulative growth / Depreciation

Investment value = $ v_{t_0} * (1+r)^t $

- `r`: growth rate

Assuming you invest `$10,000` and the ARR=`10%`, what do you get after 10 years?

In [6]:
np.fv(0.1, 10, 0, -10000)

25937.424601000024

## Discount factors

$ df = \frac{1}{(1+r)^t} $

$ v = fv * df $

- `df`: discount factor
- `v`: investment's initial value
- `fv`: investment future value

## Compound interest

Investment value = $ v_{t_0} * (1 + \frac{r}{c})^{t*c} $

- `r`: annual growth rate
- `c`: # of compounding periods per year

Consider a `$1,000` investment with a `10%` annual return, compounded quarterly (every 3 months, 4 times per year)

In [7]:
np.fv(0.1/4, 1*4, 0, -1000)

1103.8128906249995

Compounded over `30` years

In [8]:
np.fv(0.1/4, 30*4, 0, -1000)

19358.149833777778

# 1.1 Present and future values

Calculate the present value of `$100` received 3 years from now at a `1.0%` inflation rate.

In [9]:
np.pv(0.01, 3, 0, -100)

97.05901479276443

Calculate the future value of `$100` invested for 3 years at a `5.0%` average annual rate of return.

In [10]:
np.fv(0.05, 3, 0, -100)

115.76250000000002

# 1.2 Net present value & cash flows

## Net present value (NPV)

NPV is equal to the sum of all discounted cash flows. NPV is a simple cash flow valuation measure that does not allow for the comparison of different sized projects or lengths.

$ NPV = \sum^T_{t=1} \frac{C_t}{(1+r)^t} - C_0 $

- $C_t$: cashflow at time t
- `r`: discount rate

### Discount cash flow
https://www.investopedia.com/terms/d/dcf.asp

In [11]:
# Year 1-5
50.93 + 51.87 + 50.43 + 49.03 + 47.67

249.93

In [12]:
# Include 0 as we don't have cashflow for year 0
# Don't include terminal from the example
cf = np.array([0, 55, 60.5, 63.53, 66.7, 70.04])
np.npv(rate=0.08, values=cf)

249.92162512796267

# 2.0 A tale of 2 project proposals

## Internal rate of return (IRR)

The internal rate of return must be computed by solving for IRR in the NPV equation when set equal to 0. IRR can be used to compare projects of different sizes and lengths but requires an algorithmic solution and does not measure total value.

$ NPV = \sum^T_{t=1} \frac{C_t}{(1+IRR)^t} - C_t = 0 $

- `IRR`: internal rate of return

https://en.wikipedia.org/wiki/Internal_rate_of_return#Example

In [13]:
cf = np.array([-123400,36200,54800,48100])
np.irr(cf)

0.0596163785673296

# 2.1 The weighted average cost of capital (WACC)

$ WACC = F_{equity}*C_{equity} + F_{debt}*C_{debt} * (1-TR) $

- `F`: financing
- `C`: cost
- `TR`: corporate tax rate

$ F_{equity} = \frac{M_{equity}}{M_{total}} $

$ F_{debt} = \frac{M_{debt}}{M_{total}} $

$ M_{total} = M_{equity} + M_{debt}$

**WACC vs discount rate**: https://www.investopedia.com/ask/answers/052715/what-difference-between-cost-capital-and-discount-rate.asp

Calculate the WACC of a company with 12% cost of debt, 14% cost of equity, 20% debt financing and 80% equity financing, with a corporate tax rate of 35%

In [14]:
financing_equity = 0.8
cost_equity = 0.14
financing_debt = 0.2
cost_debt = 0.12
corporate_tax_rate = 0.35

WACC = financing_equity*cost_equity + financing_debt*cost_debt * (1-corporate_tax_rate)
WACC

0.12760000000000002

Calculate the NPV of a project that provides $100 in cashflow every year for 5 years. With WACC of 13%

In [15]:
cf_project1 = np.repeat(100,5)
npv_project1 = np.npv(0.13, cf_project1)
print(npv_project1)

397.4471325543258


# 2.2 Comparing 2 projects of different life spans

In [16]:
project1_cf = np.array([-100,200,300])
project2_cf = np.array([-125,100,100,100,100,100,100,100])
print('project1 length:', len(project1_cf))
print('project2 length:', len(project2_cf))

# NPV: Assume 5% discount rate for both projects
project1_npv = np.npv(0.05, project1_cf)
project2_npv = np.npv(0.05, project2_cf)
print('project1_npv:', project1_npv)
print('project2_npv:', project2_npv)

# IRR
project1_irr = np.irr(project1_cf)
project2_irr = np.irr(project2_cf)
print('project1_irr:', project1_irr)
print('project2_irr:', project2_irr)

project1 length: 3
project2 length: 8
project1_npv: 362.5850340136054
project2_npv: 453.6373397397568
project1_irr: 2.0
project2_irr: 0.7862100635772007


You can undertake multiple project 1 (3 years) over 8 years (which project 2 requires). Even though project 2 has a higher NPV, it has a smaller IRR.

## Equivalent annual annuity

Use to compare 2 projects of different lifespans in present value terms

In [17]:
project1_eea = np.pmt(rate=0.05, nper=3, pv=-1*project1_npv, fv=0)
project2_eea = np.pmt(rate=0.05, nper=8, pv=-1*project2_npv, fv=0)
print('project1_eea:', project1_eea)
print('project2_eea:', project2_eea)

project1_eea: 133.14432989690712
project2_eea: 70.18759193377169


project 1 has higher EEA than project 2

# 3.0 Mortgage basics

A mortgage is a loan that covers the remaining cost of a home after paying a percentage of the home value as downpayment.

## Converting annual rate to periodic rate
$ R_{periodic} = (1 + R_{annual})^{\frac{1}{N}} - 1 $

- `R`: rate of return
- `N`: number of payment periods per year

In [18]:
# Convert a 12% annual interest rate to the equivalent monthly rate
(1 + 0.12)**(1/12) - 1

0.009488792934583046

In [19]:
def annual_to_periodic_rate(annualRate, periods=12):
    """
    Returns a periodic rate

    Parameters
    ----------
    annualRate: float
        Represents the annual interest rate, where 0 = 0% and 1 = 100%
    periods: int
        Represents the number of payment periods per year
    """
    if annualRate is None or not isinstance(annualRate, (float)):
        raise ValueError('Please provide a valid annual rate with float datatype')
    if periods is None or not isinstance(periods, (int)):
        raise ValueError('Please provide a valid payment periods with int datatype')

    periodicRate = (1 + annualRate)**(1/periods) - 1
    return periodicRate

Calculate the monthly mortgage payment of a $400k 30 year loan at 3.8% interest

In [20]:
monthlyRate = annual_to_periodic_rate(.038)
np.pmt(rate=monthlyRate, nper=12*30, pv=400000)

-1849.145605207357

# 3.1 Amortization, principal and interest

## Amortization
`Principal` (equity): The amount of your mortgage paid that counts towards the value of the house itself

`Interest payment`: $ IP_{periodic} = RMB * R_{periodic} $

`Principal payment`: $ PP_{periodic} = MP_{periodic} - IP_{periodic} $

`PP`: prinicpal payment

`MP`: mortgage payment

`IP`: interest payment

`R`: mortgage periodic interest rate

`RMB`: remaining mortgage balance

# 3.2 Home ownership, equity and forecasting

`Home equity`: percent of the home you actually owned

$ Percent\ equity\ owned = P_{downpayment} + \frac{E_{cumulative,t}}{V_{home\ value}} $

$ E_{cumulative,t} = \sum^T_{t=1} P_{principal,t} $

$E_{cumulative,t}$: Cumulative home equity at time t

$P_{principal,t}$: Principal payment at time t

## Underwater mortgage

It is when the remaining amount you owe on your mortgage is actually higher than the value of the house itself

In [21]:
np.cumsum(np.array([1,2,3]))

array([1, 3, 6])

In [22]:
np.cumprod(np.array([1,2,3]))

array([1, 2, 6])

What's the cumulative value at each point in time of a $100 investment that grows by 3% in period 1, then 3% again in period 2, and then 5% in period 3?

In [23]:
np.cumprod(1 + np.array([0.03,0.03,0.05]))

array([1.03    , 1.0609  , 1.113945])

# 4.0 Budgeting project proposal

## Constant cumulative growth forecast

What's the cumulative growth of an investment that grows by 3% per year for 3 years?

In [24]:
np.cumprod(1 + np.repeat(0.03, 3)) - 1

array([0.03    , 0.0609  , 0.092727])

## Forecasting values from growth rates

Compute the value at each point in time of an initial $100 investment that grows by 3% per year for 3 years

In [25]:
100 * np.cumprod(1 + np.repeat(0.03, 3))

array([103.    , 106.09  , 109.2727])

# 4.1 Net worth and valuation in your personal financial life

Net worth = Assets - liabilities = equity

## Valuation
- NPV (discount rate, cash flows)
- Future cash flows, salary and expenses
- Adjust for inflation

# 4.2 The power of time and compound interest

Save $1 million over 40 years. Assume an average 7% rate of return per year

In [26]:
monthlyRate = annual_to_periodic_rate(0.07)
np.pmt(rate=monthlyRate, nper=12*40, pv=0, fv=1000000)

-404.60570652994693

If ROI is 5% per year?

In [27]:
monthlyRate = annual_to_periodic_rate(0.05)
np.pmt(rate=monthlyRate, nper=12*40, pv=0, fv=1000000)

-674.5250658283281

Save $1 million over 25 years. Assume an average 7% rate of return per year

In [28]:
monthlyRate = annual_to_periodic_rate(0.07)
np.pmt(rate=monthlyRate, nper=12*25, pv=0, fv=1000000)

-1277.070900224547

If ROI is 5% per year?

In [29]:
monthlyRate = annual_to_periodic_rate(0.05)
np.pmt(rate=monthlyRate, nper=12*25, pv=0, fv=1000000)

-1707.2580921733218

Save $1 million over 10 years, assume an average 9% rate of return per year

In [30]:
monthlyRate = annual_to_periodic_rate(0.09)
np.pmt(rate=monthlyRate, nper=12*10, pv=0, fv=1000000)

-5270.962985239908

Assume an average rate of inflation of 3% per year, what will be present value of $1 million be worth in 25 years?

In [31]:
np.fv(rate=-0.03, nper=25, pv=-1000000, pmt=0)

466974.7052543717

# 4.3 Summary

- The time value of money
- Compound interest
- Discounting and projecting cash flows
- Making rational economic decisions
- Mortgage structures
- Interest and equity
- The cost of capital
- Wealth accumulation